### ISSUE TITLE
Use eslint-plugin-userscripts & sort headers

### ISSUE THREAD

**Issue by double-beep** [userscripters/generate-headers#126]
Since 4.15, Tampermonkey uses [eslint-plugin-userscripts](https://github.com/Yash-Singh1/eslint-plugin-userscripts) to validate userscript headers. The docs are [here](https://yash-singh1.github.io/eslint-plugin-userscripts).

It'd be nice if this package used the plugin to lint headers before actually prepending them to the file.

**Comment by Oaphi** [comment]
Agreed, @double-beep. I've been trying to get it feature-complete first, and since that is mostly out of the way, it's time to look into header linting. That said, most of the rules should be already baked in (if anything supported does not pass, do let me know, I'll review and fix):

| Rule | Supported | Notes |
 | ---- | :-----------: | ------ |
| [`filename-user`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/filename-user.md) | | |
| [`no-invalid-grant`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/no-invalid-grant.md) | ✅ | built-in |
| [`no-invalid-metadata`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/no-invalid-metadata.md) | ✅ | built-in |
| [`require-name`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/require-name.md) | ✅ |  package.json, required |
| [`require-description`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/require-description.md) | ✅ | package.json, required |
| [`require-version`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/require-version.md) | ✅ | semver validation |
| [`use-homepage-and-url`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/use-homepage-and-url.md) | ✅ | package.json + overrides + default |
| [`use-download-and-update-url`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/use-download-and-update-url.md) | ✅ | package.json + overrides + default |
| [`align-attributes`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/align-attributes.md) | ✅ |  built-in, num spaces configurable |
| [`require-attribute-space-prefix`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/require-attribute-space-prefix.md) | ✅ | built-in |
| [`metadata-spacing`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/metadata-spacing.md)  | | |
| [`no-invalid-headers`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/no-invalid-headers.md) | ✅ | built-in |
| [`compat-grant`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/compat-grant.md) | ✅ | built-in |
| [`compat-headers`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/tree/main/docs/rules/compat-headers.md) | ✅ | built-in |

As for sorting - I am already looking into it: currently, the headers are sorted alphabetically, but I know that `@name` header should be the first one according to the linter. That change is coming the next patch release.

**Comment by double-beep** [comment]
@Oaphi how should we order the headers? I suggest the following (by default):

- First "group": `@name`, `@namespace`, `@description`, `@version` (not *necessarily* in that order)
- Second "group": `@author`(s) and `@contributor`s
- Third "group": `@match`/`@include`, `@exclude`
- Fourth "group": `@connect`, `@require`, `@grant` and `@run-at`
- Fifth "group": The rest

It'd be nice if the user was able to customise the order as well (though I suppose the implementation would be complicated)!

What do you think?

**Comment by Oaphi** [comment]
@double-beep  to avoid making a breaking change, I think the default behavior should be left as is (alphabetical order + `@name`  first as per liner rules), but I like the idea of providing an option to choose different sort options, specifically, the group approach you proposed above. As soon as I am out of the woods with linting (as you can see from commits, it's basically ready, but IRL keeps me from making a few finalizing touches) we can definitely address that!
